In [1]:
import pandas as pd
import numpy as np
import sklearn.ensemble as ske
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,f1_score
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.linear_model import LogisticRegression
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
data = pd.read_csv('diabetes.csv', sep=',')
print(data.head(10))
X = data.values
y = data['Outcome'].values

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1
5            5      116             74  ...                     0.201   30        0
6            3       78             50  ...                     0.248   26        1
7           10      115              0  ...                     0.134   29        0
8            2      197             70  ...                     0.158   53        1
9            8      125             96  ...                     0.232   54        1

[10 rows x 9 columns]


Test Train Split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size=0.30)

Decision Tree

In [0]:
DecisionTree = tree.DecisionTreeClassifier(max_depth=10)

In [8]:
DecisionTree.fit(X_train, y_train)
score = DecisionTree.score(X_test, y_test)
print("Accuracy : %f %%" % (score*100))
res = DecisionTree.predict(X_test)
mt = confusion_matrix(y_test, res)
print("Confusion Matrix")
print(mt)
print("False positive rate : %f %%" % ((mt[0][1] / float(sum(mt[0])))*100))
print('False negative rate : %f %%' % ( (mt[1][0] / float(sum(mt[1]))*100)))

Accuracy : 100.000000 %
Confusion Matrix
[[153   0]
 [  0  78]]
False positive rate : 0.000000 %
False negative rate : 0.000000 %


Support Vector Machine

In [0]:
SVM= svm.SVC()

In [10]:
SVM.fit(X_train, y_train)
score = SVM.score(X_test, y_test)
print("%f %%" % (score*100))
res = SVM.predict(X_test)
mt = confusion_matrix(y_test, res)
print("Confusion Matrix")
print(mt)
print("False positive rate : %f %%" % ((mt[0][1] / float(sum(mt[0])))*100))
print('False negative rate : %f %%' % ( (mt[1][0] / float(sum(mt[1]))*100)))

78.354978 %
Confusion Matrix
[[142  11]
 [ 39  39]]
False positive rate : 7.189542 %
False negative rate : 50.000000 %


Logistic Regression

In [0]:
LOGISTIC =  LogisticRegression()

In [12]:
LOGISTIC.fit(X_train, y_train)
score = LOGISTIC.score(X_test, y_test)
print("%f %%" % (score*100))
res = LOGISTIC.predict(X_test)
mt = confusion_matrix(y_test, res)
print("Confusion Matrix")
print(mt)
print("False positive rate : %f %%" % ((mt[0][1] / float(sum(mt[0])))*100))
print('False negative rate : %f %%' % ( (mt[1][0] / float(sum(mt[1]))*100)))

100.000000 %
Confusion Matrix
[[153   0]
 [  0  78]]
False positive rate : 0.000000 %
False negative rate : 0.000000 %


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


KNN

In [0]:
KNN  = KNeighborsClassifier(n_neighbors=3)

In [14]:
KNN.fit(X_train, y_train)
score = KNN.score(X_test, y_test)
print("%f %%" % (score*100))
res = KNN.predict(X_test)
mt = confusion_matrix(y_test, res)
print("Confusion Matrix")
print(mt)
print("False positive rate : %f %%" % ((mt[0][1] / float(sum(mt[0])))*100))
print('False negative rate : %f %%' % ( (mt[1][0] / float(sum(mt[1]))*100)))

69.696970 %
Confusion Matrix
[[121  32]
 [ 38  40]]
False positive rate : 20.915033 %
False negative rate : 48.717949 %


Saving Model For Future Use

In [15]:
print('Saving algorithm')
joblib.dump(DecisionTree, 'classifier.pkl')

Saving algorithm


['classifier.pkl']